title = 'P'
timelimit = 2.0
forum = ""

[[tests]]
    name = "example.in"
    number = 3

[[tests]]
    name = "random.cpp"
    number = 10

[[solutions]]
    name = "wa.cpp"
    wrong = true

[params]
    P_MIN = 1
    P_MAX = 200
    N_MIN = 1
    N_MAX = 10_000
    B_MIN = 0
