title = 'D - P'
timelimit = 2.0
forum = ""

[[tests]]
    name = "example.in"
    number = 3

[[tests]]
    name = "random.cpp"
    number = 10
	
[[tests]]
    name = "random2.cpp"
    number = 10
[[tests]]

    name = "random3.cpp"
    number = 10

[[solutions]]
    name = "wa.cpp"
    wrong = true
	
[[solutions]]
    name = "correct2.cpp"

[[solutions]]
    name = "Endered.cpp"

[[solutions]]
    name = "keymoon.cpp"

[[solutions]]
    name = "mo3tthi.cpp"

[[solutions]]
    name = "tubuann.cpp"

[[solutions]]
    name = "tubuann_TLE.cpp"
    allow_tle = true

[params]
    P_MIN = 1
    P_MAX = 500
    N_MIN = 1
    N_MAX = 500
    A_MIN = 0
