title = 'D - P'
timelimit = 2.0
forum = ""

[[tests]]
    name = "example.in"
    number = 3

[[tests]]
    name = "random.cpp"
    number = 10

[[solutions]]
    name = "wa.cpp"
    wrong = true
	
[[solutions]]
    name = "correct2.cpp"

[[solutions]]
    name = "Endered.cpp"

[[solutions]]
    name = "keymoon.cpp"

[[solutions]]
    name = "mo3tthi.cpp"

[params]
    P_MIN = 1
    P_MAX = 100
    N_MIN = 1
    N_MAX = 10_000
    A_MIN = 0
