title = 'F - LotOfMountains'
timelimit = 2.0
forum = ""

[[tests]]
    name = "example.in"
    number = 3

[[tests]]
    name = "random.cpp"
    number = 10

[[tests]]
    name = "random-big.cpp"
    number = 5

[[solutions]]
    name = "wa-1e-5.cpp"
    wrong = true

[[solutions]]
    name = "tle.cpp"
    allow_tle = true

[[solutions]]
    name = "heuristic.cpp"
    wrong = true

[[solutions]]
    name = "rel-1e-7.cpp"

[params]
    N_MIN = 1
    N_MAX = 100_000
    R_MIN = 1
    R_MAX = 1_000_000
    H_MIN = 1
    H_MAX = 100_000_000
    X_MIN = 1
    X_MAX = 100_000_000
