title = 'H - Islands'
timelimit = 8.0
forum = ""

[[tests]]
    name = "example.in"
    number = 2

[[tests]]
    name = "small.cpp"
    number = 30

[[tests]]
    name = "random.cpp"
    number = 5

[[tests]]
    name = "maximum.cpp"
    number = 5

[[tests]]
    name = "itimatu.cpp"
    number = 5

[[solutions]]
    name = "bf.cpp"
    wrong = true

[[solutions]]
    name = "tubuann.cpp"

[[solutions]]
    name = "Luzhiled.cpp"

#[[solutions]]
#    name = "Endered.cpp"

[params]
    HW_MIN = 1
    HW_MAX = 1000
    Q_MIN = 1
    Q_MAX = 100_000
    SMALL_HW_MIN = 1
    SMALL_HW_MAX = 100
    SMALL_Q_MIN = 1
    SMALL_Q_MAX = 100_000
    P_ALL = 5
    mod = 1024
    roll = 427
    cst = 821
