[[problem/A_rta]]
    "name" = "A - RTA"

[[problem/B_LiChaoSegmentTree]]
    "name" = "B - LiChaoSegmentTree"

[[problem/C_BrokenMachine]]
    "name" = "C - Broken Machine"

[[problem/D_P]]
    "name" = "D - P"

[[problem/E_MonochromeStone]]
    "name" = "E - Monochrome Stone"

[[problem/F-lot-of-mountains]]
    "name" = "F - LotOfMountains"

[[problem/G_Connect_the_dots]]
    "name" = "G - Connect the dots"

[[problem/H_Islands]]
    "name" = "H - Islands"

[[problem/I_origami]]
    "name" = "I - Origami"

[[problem/J_DEG_MUL_SUM]]
    "name" = "J - DEG MUL SUM"

[[problem/K_Zor]]
    "name" = "K - Zor"

