title = 'B - LiChaoSegmentTree'
timelimit = 2.0
forum = ""

[[tests]]
    name = "example.in"
    number = 3

[[tests]]
    name = "random.cpp"
    number = 10

[[solutions]]
    name = "wa.cpp"
    wrong = true

[[solutions]]
    name = "Endered.cpp"

[[solutions]]
    name = "Luzhiled.cpp"

[[solutions]]
    name = "shot.cpp"

[[solutions]]
    name = "keymoon.cpp"

[params]
    N_MIN = 1
    N_MAX = 5000
    Q_MIN = 1
    Q_MAX = 5000
    AB_ABS = 1_000_000_000
    P_ABS = 1_000_000_000
