title = 'LotOfMountains'
timelimit = 2.0
forum = ""

[[tests]]
    name = "example.in"
    number = 2

[[tests]]
    name = "random.cpp"
    number = 10

[params]
    N_MIN = 1
    N_MAX = 100_000
    R_MIN = 1
    R_MAX = 1_000_000
    H_MIN = 1
    H_MAX = 100_000_000
    X_MIN = 1
    X_MAX = 100_000_000
