title = 'G - Connect the dots'
timelimit = 2.0
forum = ""

[[tests]]
    name = "example.in"
    number = 2

[[tests]]
    name = "random.cpp"
    number = 5
[[tests]]
    name = "mini.cpp"
    number = 5
[[tests]]
    name = "large.cpp"
    number = 10
[[tests]]
    name = "handmade.in"
    number = 1

[[solutions]]
    name = "wa.cpp"
    wrong = true

[params]
    N_MIN = 2
    N_MAX = 100_000
    XY_MIN = -1_000_000_000
    XY_MAX = 1_000_000_000
