title = 'G - Connect the dots'
timelimit = 3.0
forum = ""

[[tests]]
    name = "example.in"
    number = 3

[[tests]]
    name = "random.cpp"
    number = 5

[[tests]]
    name = "mini.cpp"
    number = 3

[[tests]]
    name = "large.cpp"
    number = 5

[[tests]]
    name = "special_mountain_tate.cpp"
    number = 1

[[tests]]
    name = "special_mountain_tate_rev.cpp"
    number = 1

[[tests]]
    name = "special_mountain_yoko.cpp"
    number = 1

[[tests]]
    name = "special_long_tate.cpp"
    number = 1

[[tests]]
    name = "special_long_yoko.cpp"
    number = 1

[[tests]]
    name = "special_pole_random.cpp"
    number = 15
[[tests]]
    name = "special_pole_sort.cpp"
    number = 10
[[tests]]
    name = "special_spiral.cpp"
    number = 2
[[tests]]
    name = "special_spiral_rev.cpp"
    number = 2
[[tests]]
    name = "special_spiral_zero.cpp"
    number = 2
[[tests]]
    name = "special_square_random.cpp"
    number = 3


[[tests]]
    name = "handmade.in"
    number = 3

[[solutions]]
    name = "wa.cpp"
    wrong = true

[[solutions]]
    name = "Luzhiled.cpp"

[[solutions]]
    name = "beet.cpp"

[[solutions]]
    name = "tubuann.cpp"

[[solutions]]
    name = "moritaoy_naive.cpp"
    allow_tle = true

[params]
    N_MIN = 2
    N_MAX = 100_000
    XY_ABS = 1_000_000_000
