title = 'RTA'
timelimit = 2.0
forum = ""

[[tests]]
    name = "example.in"
    number = 2

[[tests]]
    name = "random.cpp"
    number = 10

[[solutions]]
    name = "wa.cpp"
    wrong = true

[[solutions]]
    name = "beet.cpp"

[[solutions]]
    name = "keymoon.cpp"

[[solutions]]
    name = "Endered.cpp"

[params]
    A_AND_B_MIN = 0
    A_AND_B_MAX = 100_000_000
