title = 'RTA'
timelimit = 2.0
forum = ""

[[tests]]
    name = "example.in"
    number = 2

[[tests]]
    name = "random.cpp"
    number = 10

[[solutions]]
    name = "wa.cpp"
    wrong = true

[[solutions]]
    name = "beet.cpp"

[[solutions]]
<<<<<<< HEAD
    name = "shot.cpp"
=======
    name = "Endered.cpp"
>>>>>>> e7290fd44d909a62b81f351f5d6f4470a1e68c78

[params]
    A_AND_B_MIN = 0
    A_AND_B_MAX = 100_000_000
