title = 'I - Origami'
timelimit = 2.0
forum = ""

[[tests]]
    name = "example.in"
    number = 4

[[tests]]
    name = "random_small.cpp"
    number = 5

[[tests]]
    name = "random.cpp"
    number = 20

[[tests]]
    name = "random_max.cpp"
    number = 10

[[solutions]]
    name = "tubuann.cpp"

[[solutions]]
name = "c7c7c7c7.cpp"

[[solutions]]
name = "Luzhiled.cpp"

[[solutions]]
name = "beet.cpp"

[[solutions]]
    name = "wa.cpp"
    wrong = true

[params]
    N_MIN = 3
    N_MAX = 30
    M_MIN = 1
    M_MAX = 5
    xy_abs = 1000
    significant_digit = 4
    param_EPS = 1e-4