title = 'I - Origami'
timelimit = 2.0
forum = ""

[[tests]]
    name = "example.in"
    number = 4

[[tests]]
    name = "random.cpp"
    number = 10

[[tests]]
    name = "random_small.cpp"
    number = 5

[[solutions]]
    name = "wa.cpp"
    wrong = true

[params]
    N_MIN = 3
    N_MAX = 1000
    M_MIN = 1
    M_MAX = 10
    xy_MIN = -1e4
    xy_MAX = 1e4
    significant_digit = 6
    param_EPS = 1e-6