title = 'E - Monochrome Stone'
timelimit = 2.0
forum = ""

[[tests]]
    name = "example.in"
    number = 3

[[tests]]
    name = "handmade.in"
    number = 4

[[tests]]
    name = "random.cpp"
    number = 5

[[tests]]
    name = "random_large.cpp"
    number = 8

[[tests]]
    name = "random_max.cpp"
    number = 8

[[solutions]]
    name = "wa.cpp"
    wrong = true

[[solutions]]
    name = "correct2.cpp"

[[solutions]]
    name = "Endered.cpp"

[[solutions]]
    name = "toyama.cpp"

[[solutions]]
    name = "Luzhiled.cpp"

[[solutions]]
    name = "keymoon.cpp"

[[solutions]]
    name = "keymoon_wa.cpp"
    wrong = true

[[solutions]]
    name = "tubuann.cpp"

[[solutions]]
    name = "tubuann_TLE.cpp"
    allow_tle = true

[[solutions]]
    name = "tubuann_TLE_fast.cpp"
    allow_tle = true

[[solutions]]
    name = "beet.cpp"

[[solutions]]
    name = "beet_wa.cpp"
    wrong = true

[params]
    N_P_K_MIN = 1
    N_P_K_MAX = 5000
    W_B_MIN = 1
    W_B_MAX = 5000
