title = 'RTA'
timelimit = 2.0
forum = ""

[[tests]]
    name = "example.in"
    number = 1

[[tests]]
    name = "handmade.in"
    number = 6

[[tests]]
    name = "random.cpp"
    number = 10

[[solutions]]
   name = "self_loop.cpp"
   wrong = true

[[solutions]]
   name = "extra_out.cpp"
   wrong = true

[params]
    N_MIN = 1
    N_MAX = 100
    M_MIN = 0
    M_MAX = 1000
