title = 'C - Broken Machine'
timelimit = 2.0
forum = ""

[[tests]]
   name = "example.in"
   number = 1

[[tests]]
   name = "handmade.in"
   number = 5

[[tests]]
   name = "random.cpp"
   number = 10

[[solutions]]
   name = "self_loop.cpp"
   wrong = true

[[solutions]]
   name = "extra_out.cpp"
   wrong = true

[[solutions]]
   name = "beet.cpp"

[[solutions]]
   name = "Endered_wa.cpp"
   wrong = true

[[solutions]]
   name = "toyama_wa.cpp"
   wrong = true

[[solutions]]
   name = "toyama.cpp"

[params]
   N_MIN = 2
   N_MAX = 100
   M_MIN = 1
   M_MAX = 1000
