title = 'K - Zor'
timelimit = 8.0
forum = ""

[[tests]]
    name = "example.in"
    number = 3

[[tests]]
    name = "random.cpp"
    number = 10

[[tests]]
    name = "maximum.cpp"
    number = 5

[[tests]]
    name = "random2.cpp"
    number = 10

[[tests]]
    name = "random_loop.cpp"
    number = 10

[[tests]]
    name = "small_loop.cpp"
    number = 10

[[tests]]
    name = "large_loop.cpp"
    number = 10

[[tests]]
    name = "maximum_loop.cpp"
    number = 10

[[solutions]]
    name = "tubuann3log.cpp"

[[solutions]]
    name = "tubuann4lin.cpp"
    allow_tle = true

[[solutions]]
    name = "tubuann4dbl.cpp"
    allow_tle = true

[[solutions]]
    name = "Endered.cpp"

[params]
    MIN_K = 1
    MAX_K = 1000
    MIN_N = 1
    MAX_N = 10
    small_loop = 13
    large_loop = 497
    maximum_loop = 990
    mod = 998244353
