title = 'K - Zor'
timelimit = 2.0
forum = ""

[[tests]]
    name = "example.in"
    number = 2

[[tests]]
    name = "random.cpp"
    number = 10

[[tests]]
    name = "maximum.cpp"
    number = 5

[[tests]]
    name = "random2.cpp"
    number = 10

[[tests]]
    name = "random_loop.cpp"
    number = 10

[[tests]]
    name = "small_loop.cpp"
    number = 10

[[tests]]
    name = "large_loop.cpp"
    number = 10

[[tests]]
    name = "maximum_loop.cpp"
    number = 10

[[solutions]]
    name = "tubuann.cpp"

[[solutions]]
    name = "tubuann2.cpp"

#[[solutions]]
#    name = "Endered.cpp"

[params]
    MIN_K = 1
    MAX_K = 300
    MIN_N = 1
    MAX_N = 10
    small_loop = 13
    large_loop = 149
    maximum_loop = 290
    mod = 998244353
