title = 'Origami'
timelimit = 2.0
forum = ""

[[tests]]
    name = "example.in"
    number = 2

[[tests]]
    name = "random.cpp"
    number = 10

[params]
    P_MIN = 1
    P_MAX = 100_000
    N_MIN = 1
    N_MAX = 1000
    M_MIN = 1
    M_MAX = 10
    xy_MIN = -1e9
    xy_MAX = 1e9
