title = 'Monochrome Stone'
timelimit = 2.0
forum = ""

[[tests]]
    name = "example.in"
    number = 2

[[tests]]
    name = "random.cpp"
    number = 10

[[solutions]]
    name = "wa.cpp"
    wrong = true

[params]
    N_W_B_MIN = 1
    N_W_B_MAX = 1000
    
