name: Diff

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  echo-commit-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name : GITHUB CONTEXT
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  gcc-ubuntu-diffrun:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[run ci]') == true
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.5.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.5.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --user -r requirements.txt
      - name: Print verison file
        run: |
          ./ci_generate.py --print-version | tee versions.json
      - uses: actions/cache@v1
        with:
          path: cache
          key: ${{ runner.os }}-cache-${{ hashFiles('versions.json')}}
          restore-keys: |
            ${{ runner.os }}-cache-
      - name: Run generate.py on gcc
        run: |
          ulimit -s unlimited
          ./ci_generate.py --htmldir=/tmp/html
      - name: Archive problem statements
        uses: actions/upload-artifact@v1
        with:
          name: statements
          path: /tmp/html
